CREATE DATABASE ArecologicoERP;
GO

USE ArecologicoERP;
GO

CREATE TABLE MARCA (
    COD_MARCA   INT          NOT NULL IDENTITY(1,1),
    NOME_MARCA  VARCHAR(100) NOT NULL,   -- Ex: LG, Elgin, Samsung
    CONSTRAINT PK_MARCA PRIMARY KEY (COD_MARCA)
);

CREATE TABLE EQUIPAMENTO (
    COD_EQUIPAMENTO  INT          NOT NULL IDENTITY(1,1),
    MODELO           VARCHAR(100) NOT NULL,
    BTUS             INT          NOT NULL,
    COD_MARCA        INT          NOT NULL,
    CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (COD_EQUIPAMENTO),
    CONSTRAINT FK_EQUIPAMENTO_MARCA FOREIGN KEY (COD_MARCA)
        REFERENCES MARCA (COD_MARCA)
);

CREATE TABLE TIPO_CONTRATO (
    COD_TIPO_CONTRATO  INT          NOT NULL IDENTITY(1,1),
    TIPO_CONTRATO      VARCHAR(50)  NOT NULL,   -- Mensal, Semestral...
    CONSTRAINT PK_TIPO_CONTRATO PRIMARY KEY (COD_TIPO_CONTRATO)
);

CREATE TABLE TIPO_PAGAMENTO (
    COD_TIPO_PAGAMENTO  INT         NOT NULL IDENTITY(1,1),
    TIPO_PAGAMENTO      VARCHAR(50) NOT NULL,   -- Pix, Cartão, Boleto
    CONSTRAINT PK_TIPO_PAGAMENTO PRIMARY KEY (COD_TIPO_PAGAMENTO)
);

CREATE TABLE TIPO_OS (
    COD_TIPO_OS  INT         NOT NULL IDENTITY(1,1),
    TIPO_OS      VARCHAR(50) NOT NULL,   -- Preventiva, Corretiva
    CONSTRAINT PK_TIPO_OS PRIMARY KEY (COD_TIPO_OS)
);

CREATE TABLE SERVICO (
    COD_SERVICO          INT            NOT NULL IDENTITY(1,1),
    DESCRICAO_SERVICO    VARCHAR(300)   NOT NULL,
    VALOR_SERVICO        DECIMAL(10,2)  NOT NULL,
    DATA_SERVICO_INICIO  DATE           NULL,
    DATA_SERVICO_FIM     DATE           NULL,
    CONSTRAINT PK_SERVICO PRIMARY KEY (COD_SERVICO)
);

CREATE TABLE PESSOA (
    COD_PESSOA   INT          NOT NULL IDENTITY(1,1),
    NOME         VARCHAR(150) NOT NULL,
    CPF          CHAR(11)     NULL,
    RG           VARCHAR(20)  NULL,
    ENDERECO     VARCHAR(200) NULL,
    NUMERO_CASA  VARCHAR(10)  NULL,
    CEP          CHAR(8)      NULL,
    CIDADE       VARCHAR(100) NULL,
    UF           CHAR(2)      NULL,
    TELEFONE     VARCHAR(20)  NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (COD_PESSOA)
);

CREATE TABLE CLIENTE (
    COD_PESSOA        INT         NOT NULL,
    EMAIL             VARCHAR(150) NULL,
    TIPO              CHAR(1)     NOT NULL,  -- 'F' = Física / 'J' = Jurídica
    DATA_NASCIMENTO   DATE        NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_PESSOA),
    CONSTRAINT FK_CLIENTE_PESSOA FOREIGN KEY (COD_PESSOA)
        REFERENCES PESSOA (COD_PESSOA),
    CONSTRAINT CHK_CLIENTE_TIPO CHECK (TIPO IN ('F', 'J'))
);

CREATE TABLE PRESTADOR_SERVICO (
    COD_PESSOA  INT            NOT NULL,
    PAGAMENTO   DECIMAL(10,2)  NULL,   -- valor/forma de pagamento ao prestador
    CONSTRAINT PK_PRESTADOR_SERVICO PRIMARY KEY (COD_PESSOA),
    CONSTRAINT FK_PRESTADOR_PESSOA FOREIGN KEY (COD_PESSOA)
        REFERENCES PESSOA (COD_PESSOA)
);



CREATE TABLE CONTRATO (
    COD_CONTRATO       INT            NOT NULL IDENTITY(1,1),
    DESCRICAO_CONTRATO VARCHAR(500)   NULL,
    VALOR_CONTRATO     DECIMAL(10,2)  NOT NULL,
    DATA_CONTRATO_INICIO DATE         NOT NULL,
    DATA_CONTRATO_FIM    DATE         NOT NULL,
    COD_TIPO_CONTRATO  INT            NOT NULL,
    COD_PESSOA         INT            NOT NULL,   -- FK → CLIENTE
    CONSTRAINT PK_CONTRATO PRIMARY KEY (COD_CONTRATO),
    CONSTRAINT FK_CONTRATO_TIPO FOREIGN KEY (COD_TIPO_CONTRATO)
        REFERENCES TIPO_CONTRATO (COD_TIPO_CONTRATO),
    CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (COD_PESSOA)
        REFERENCES CLIENTE (COD_PESSOA)
);

CREATE TABLE CONTRATO_EQUIPAMENTO (
    COD_CONTRATO     INT  NOT NULL,
    COD_EQUIPAMENTO  INT  NOT NULL,
    CONSTRAINT PK_CONTRATO_EQUIPAMENTO PRIMARY KEY (COD_CONTRATO, COD_EQUIPAMENTO),
    CONSTRAINT FK_CE_CONTRATO FOREIGN KEY (COD_CONTRATO)
        REFERENCES CONTRATO (COD_CONTRATO),
    CONSTRAINT FK_CE_EQUIPAMENTO FOREIGN KEY (COD_EQUIPAMENTO)
        REFERENCES EQUIPAMENTO (COD_EQUIPAMENTO)
);


CREATE TABLE ORDEM_SERVICO (
    COD_OS               INT            NOT NULL IDENTITY(1,1),
    OBS                  VARCHAR(500)   NULL,
    VALOR_TOTAL          DECIMAL(10,2)  NULL,
    DATA_ABERTURA        DATE           NOT NULL,
    STATUS               VARCHAR(50)    NOT NULL,  -- Aberta, Em andamento, Concluída...
    DATA_EXECUCAO        DATE           NULL,
    DESCRICAO_PROBLEMA   VARCHAR(500)   NULL,
    DESCRICAO_EXECUTADO  VARCHAR(500)   NULL,
    -- Chaves estrangeiras
    COD_PESSOA_CLIENTE   INT            NOT NULL,  -- FK → CLIENTE
    COD_PESSOA_PRESTADOR INT            NOT NULL,  -- FK → PRESTADOR_SERVICO
    COD_TIPO_OS          INT            NULL,      -- FK → TIPO_OS
    COD_TIPO_PAGAMENTO   INT            NULL,      -- FK → TIPO_PAGAMENTO
    CONSTRAINT PK_ORDEM_SERVICO PRIMARY KEY (COD_OS),
    CONSTRAINT FK_OS_CLIENTE FOREIGN KEY (COD_PESSOA_CLIENTE)
        REFERENCES CLIENTE (COD_PESSOA),
    CONSTRAINT FK_OS_PRESTADOR FOREIGN KEY (COD_PESSOA_PRESTADOR)
        REFERENCES PRESTADOR_SERVICO (COD_PESSOA),
    CONSTRAINT FK_OS_TIPO_OS FOREIGN KEY (COD_TIPO_OS)
        REFERENCES TIPO_OS (COD_TIPO_OS),
    CONSTRAINT FK_OS_TIPO_PAGAMENTO FOREIGN KEY (COD_TIPO_PAGAMENTO)
        REFERENCES TIPO_PAGAMENTO (COD_TIPO_PAGAMENTO)
);

CREATE TABLE ORDEM_SERVICO_SERVICO (
    COD_OS       INT  NOT NULL,
    COD_SERVICO  INT  NOT NULL,
    CONSTRAINT PK_OS_SERVICO PRIMARY KEY (COD_OS, COD_SERVICO),
    CONSTRAINT FK_OSS_OS FOREIGN KEY (COD_OS)
        REFERENCES ORDEM_SERVICO (COD_OS),
    CONSTRAINT FK_OSS_SERVICO FOREIGN KEY (COD_SERVICO)
        REFERENCES SERVICO (COD_SERVICO)
);


CREATE TABLE CONTRATO_OS (
    COD_CONTRATO  INT  NOT NULL,
    COD_OS        INT  NOT NULL,
    CONSTRAINT PK_CONTRATO_OS PRIMARY KEY (COD_CONTRATO, COD_OS),
    CONSTRAINT FK_COS_CONTRATO FOREIGN KEY (COD_CONTRATO)
        REFERENCES CONTRATO (COD_CONTRATO),
    CONSTRAINT FK_COS_OS FOREIGN KEY (COD_OS)
        REFERENCES ORDEM_SERVICO (COD_OS)
);
