INSERT INTO MARCA (NOME_MARCA) VALUES ('LG');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Elgin');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Samsung');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Midea');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Daikin');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Springer');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Trane');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Carrier');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Hitachi');
INSERT INTO MARCA (NOME_MARCA) VALUES ('Gree');

INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Split Hi-Wall S4NQ09WA3',  9000,  1);  -- LG
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Split Hi-Wall S4NQ12WA3',  12000, 1);  -- LG
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Split Eco HWFI09B2IA',     9000,  2);  -- Elgin
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Split Eco HWFI12B2IA',     12000, 2);  -- Elgin
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('WindFree AR09BSHCBWKNAZ', 9000,  3);  -- Samsung
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('WindFree AR12BSHCBWKNAZ', 12000, 3);  -- Samsung
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Olímpico Inverter 18000', 18000, 4);  -- Midea
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('FTK09TVMW',               9000,  5);  -- Daikin
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Springer Midea 24000',    24000, 6);  -- Springer
INSERT INTO EQUIPAMENTO (MODELO, BTUS, COD_MARCA) VALUES ('Carrier X-Power 18000',   18000, 8);  -- Carrier

INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Mensal');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Trimestral');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Semestral');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Anual');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Bianual');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Avulso');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Corporativo Mensal');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Corporativo Anual');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Emergencial');
INSERT INTO TIPO_CONTRATO (TIPO_CONTRATO) VALUES ('Preventivo Plus');
 
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Pix');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Cartão de Crédito');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Cartão de Débito');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Boleto Bancário');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Transferência Bancária');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Dinheiro');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Cheque');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Crédito em Conta');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Parcelado no Cartão');
INSERT INTO TIPO_PAGAMENTO (TIPO_PAGAMENTO) VALUES ('Convênio Empresarial');

INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Preventiva');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Corretiva');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Instalação');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Desinstalação');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Higienização');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Recarga de Gás');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Revisão Geral');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Garantia');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Orçamento');
INSERT INTO TIPO_OS (TIPO_OS) VALUES ('Emergencial');

INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Limpeza de filtro',              80.00,  '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Higienização completa',          250.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Recarga de gás R410A',           350.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Instalação de equipamento',      400.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Revisão elétrica',               180.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Substituição de placa eletrônica',600.00,'2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Limpeza da serpentina',          200.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Desinstalação de equipamento',   250.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Manutenção preventiva completa', 320.00, '2025-01-01', NULL);
INSERT INTO SERVICO (DESCRICAO_SERVICO, VALOR_SERVICO, DATA_SERVICO_INICIO, DATA_SERVICO_FIM)
    VALUES ('Troca de capacitor',             150.00, '2025-01-01', NULL);


INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Carlos Eduardo Souza',  '12345678901', '1234567', 'Rua das Flores',       '100', '15025010', 'São José do Rio Preto', 'SP', '17991110001');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Ana Paula Lima',        '23456789012', '2345678', 'Av. Bady Bassitt',     '250', '15025020', 'São José do Rio Preto', 'SP', '17992220002');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('TechFrio Ltda',         '34567890113', '3456789', 'Rua do Comércio',      '10',  '15025030', 'São José do Rio Preto', 'SP', '17993330003');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Marcos Antônio Reis',   '45678901214', '4567890', 'Rua XV de Novembro',   '300', '15025040', 'Mirassol',              'SP', '17994440004');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Fernanda Costa',        '56789012315', '5678901', 'Av. Alberto Andaló',   '400', '15025050', 'São José do Rio Preto', 'SP', '17995550005');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Climatize Soluções',    '67890123416', '6789012', 'Rua Pio XII',          '55',  '15025060', 'Catanduva',             'SP', '17996660006');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('João Pedro Alves',      '78901234517', '7890123', 'Rua Sete de Setembro', '120', '15025070', 'São José do Rio Preto', 'SP', '17997770007');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Refrigeração Norte ME', '89012345618', '8901234', 'Av. Philadélfia',      '800', '15025080', 'São José do Rio Preto', 'SP', '17998880008');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Beatriz Mendonça',      '90123456719', '9012345', 'Rua Floriano Peixoto', '90',  '15025090', 'Votuporanga',           'SP', '17999990009');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Roberto Faria',         '01234567820', '0123456', 'Rua Marechal Rondon',  '45',  '15025100', 'São José do Rio Preto', 'SP', '17990000010');


INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (1,  'carlos.souza@email.com',      'F', '1985-03-15');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (2,  'ana.lima@email.com',           'F', '1990-07-22');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (3,  'contato@techfrio.com.br',      'J', NULL);
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (4,  'marcos.reis@email.com',        'F', '1978-11-05');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (5,  'fernanda.costa@email.com',     'F', '1995-02-28');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (6,  'contato@climatize.com.br',     'J', NULL);
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (7,  'joao.alves@email.com',         'F', '1988-09-10');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (8,  'contato@refrinorte.com.br',    'J', NULL);
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (9,  'beatriz.mendonca@email.com',   'F', '2000-06-18');
INSERT INTO CLIENTE (COD_PESSOA, EMAIL, TIPO, DATA_NASCIMENTO)
    VALUES (10, 'roberto.faria@email.com',      'F', '1972-12-30');

INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Lucas Técnico Silva',    '11122233344', '1112223', 'Rua A', '1', '15000001', 'São José do Rio Preto', 'SP', '17911111111');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Pedro Técnico Rocha',    '22233344455', '2223334', 'Rua B', '2', '15000002', 'São José do Rio Preto', 'SP', '17922222222');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Rafael Técnico Melo',    '33344455566', '3334445', 'Rua C', '3', '15000003', 'São José do Rio Preto', 'SP', '17933333333');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Diego Técnico Nunes',    '44455566677', '4445556', 'Rua D', '4', '15000004', 'São José do Rio Preto', 'SP', '17944444444');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Thiago Técnico Pires',   '55566677788', '5556667', 'Rua E', '5', '15000005', 'São José do Rio Preto', 'SP', '17955555555');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Bruno Técnico Castro',   '66677788899', '6667778', 'Rua F', '6', '15000006', 'São José do Rio Preto', 'SP', '17966666666');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('André Técnico Ramos',    '77788899900', '7778889', 'Rua G', '7', '15000007', 'São José do Rio Preto', 'SP', '17977777777');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Felipe Técnico Sousa',   '88899900011', '8889990', 'Rua H', '8', '15000008', 'São José do Rio Preto', 'SP', '17988888888');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Vitor Técnico Lima',     '99900011122', '9990001', 'Rua I', '9', '15000009', 'São José do Rio Preto', 'SP', '17999999999');
INSERT INTO PESSOA (NOME, CPF, RG, ENDERECO, NUMERO_CASA, CEP, CIDADE, UF, TELEFONE)
    VALUES ('Guilherme Técnico Dias', '00011122233', '0001112', 'Rua J', '10','15000010', 'São José do Rio Preto', 'SP', '17900000000');

INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (11, 1800.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (12, 2000.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (13, 1600.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (14, 2200.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (15, 1900.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (16, 2100.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (17, 1750.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (18, 2300.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (19, 1850.00);
INSERT INTO PRESTADOR_SERVICO (COD_PESSOA, PAGAMENTO) VALUES (20, 2050.00);


INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Manutenção preventiva mensal - TechFrio',       1500.00, '2025-01-01', '2025-01-31', 1, 3);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato trimestral residencial - Carlos',       900.00, '2025-01-01', '2025-03-31', 2, 1);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato semestral - Climatize',                3200.00, '2025-01-01', '2025-06-30', 3, 6);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato anual corporativo - Refri Norte',      8000.00, '2025-01-01', '2025-12-31', 4, 8);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Plano preventivo plus - Ana Paula',              600.00, '2025-02-01', '2026-01-31', 10, 2);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato mensal - João Pedro',                   450.00, '2025-03-01', '2025-03-31', 1, 7);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Renovação trimestral - TechFrio',               1500.00, '2025-02-01', '2025-04-30', 2, 3);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato bianual - Marcos Reis',                5000.00, '2025-01-01', '2026-12-31', 5, 4);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Plano semestral - Fernanda Costa',               750.00, '2025-04-01', '2025-09-30', 3, 5);
INSERT INTO CONTRATO (DESCRICAO_CONTRATO, VALOR_CONTRATO, DATA_CONTRATO_INICIO, DATA_CONTRATO_FIM, COD_TIPO_CONTRATO, COD_PESSOA)
    VALUES ('Contrato anual - Beatriz Mendonça',             1200.00, '2025-05-01', '2026-04-30', 4, 9);

INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (1,  1);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (1,  2);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (2,  3);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (3,  4);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (3,  5);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (4,  1);  -- mesmo equip. do contrato 1 renovado
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (4,  6);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (5,  7);
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (7,  1);  -- renovação contrato 1 → mesmo equip.
INSERT INTO CONTRATO_EQUIPAMENTO (COD_CONTRATO, COD_EQUIPAMENTO) VALUES (7,  2);  -- renovação contrato 1 → mesmo equip.

INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Limpeza mensal programada',           80.00,  '2025-01-10', 'Concluída',    '2025-01-10', 'Filtro sujo',             'Filtro limpo',             3, 11, 1, 1);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Ar não gela',                        350.00, '2025-01-15', 'Concluída',    '2025-01-16', 'Falta de gás R410A',      'Recarga de gás realizada', 1, 12, 2, 4);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Instalação novo equipamento',        400.00, '2025-01-20', 'Concluída',    '2025-01-21', 'Novo equipamento',        'Equipamento instalado',    6, 13, 3, 1);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Revisão preventiva trimestral',      320.00, '2025-02-05', 'Concluída',    '2025-02-05', 'Revisão de rotina',       'Manutenção preventiva ok', 8, 14, 1, 2);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Barulho estranho no equipamento',    150.00, '2025-02-12', 'Concluída',    '2025-02-13', 'Capacitor com defeito',   'Capacitor substituído',    2, 15, 2, 1);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Higienização completa solicitada',   250.00, '2025-03-01', 'Concluída',    '2025-03-01', 'Higienização programada', 'Higienização concluída',   7, 16, 5, 4);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Placa com defeito',                  600.00, '2025-03-10', 'Em andamento', NULL,          'Placa eletrônica queimada',NULL,                        4, 17, 2, NULL);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('OS sem contrato - cliente avulso',    80.00, '2025-03-15', 'Concluída',    '2025-03-15', 'Filtro entupido',         'Limpeza realizada',        10, 18, 1, 1);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Revisão semestral contrato Beatriz', 320.00, '2025-05-10', 'Aberta',       NULL,          'Revisão programada',      NULL,                       9, 19, 1, NULL);
INSERT INTO ORDEM_SERVICO (OBS, VALOR_TOTAL, DATA_ABERTURA, STATUS, DATA_EXECUCAO, DESCRICAO_PROBLEMA, DESCRICAO_EXECUTADO, COD_PESSOA_CLIENTE, COD_PESSOA_PRESTADOR, COD_TIPO_OS, COD_TIPO_PAGAMENTO)
    VALUES ('Limpeza mensal renovação TechFrio',   80.00, '2025-02-10', 'Concluída',    '2025-02-10', 'Filtro sujo',             'Filtro limpo',              3, 20, 1, 1);

INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (1,  1);   -- OS 1  → Limpeza de filtro
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (2,  3);   -- OS 2  → Recarga de gás
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (3,  4);   -- OS 3  → Instalação
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (4,  9);   -- OS 4  → Manutenção preventiva completa
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (4,  5);   -- OS 4  → Revisão elétrica também
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (5,  10);  -- OS 5  → Troca de capacitor
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (6,  2);   -- OS 6  → Higienização completa
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (7,  6);   -- OS 7  → Substituição de placa
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (8,  1);   -- OS 8  → Limpeza de filtro (avulso)
INSERT INTO ORDEM_SERVICO_SERVICO (COD_OS, COD_SERVICO) VALUES (10, 1);   -- OS 10 → Limpeza de filtro renovação

INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (1,  1);   -- Contrato TechFrio mensal → OS limpeza jan
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (2,  2);   -- Contrato trimestral Carlos → OS recarga gás
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (3,  3);   -- Contrato semestral Climatize → OS instalação
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (4,  4);   -- Contrato anual Refri Norte → OS revisão
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (5,  5);   -- Contrato preventivo Ana → OS capacitor
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (6,  6);   -- Contrato mensal João → OS higienização
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (8,  7);   -- Contrato bianual Marcos → OS placa
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (10, 9);   -- Contrato anual Beatriz → OS revisão semestral
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (7,  10);  -- Renovação TechFrio → OS limpeza fev
INSERT INTO CONTRATO_OS (COD_CONTRATO, COD_OS) VALUES (1,  10);  -- Contrato original TechFrio tb vinculado à OS 10 (N:N)
